<?php

$aaData = array();
$count  = count($this->result['data']);

foreach($this->result['data'] as $result) {
	$nuPreco = number_format($result['nuPreco'],2,',','');
    $aaData[] = array(
        $result['noProduto'],
        $nuPreco
    );
}

echo json_encode(array(
    'aaData' => $aaData,
    'iTotalDisplayRecords' => $count,
    'iTotalRecords' => $this->result['total'],
    'sEcho' => $this->result['sEcho']
));
