<?php echo $this->doctype();?>
<html>
<head>
	<title>Loja Virtual</title>
    <meta charset="utf-8" />
    <!-- CSS GERAL INICIO -->
    <?php
        $this->headLink()
             ->setStylesheet('/css/bootstrap.min.css')
             ->appendStylesheet('/css/estilo.css')
             ->appendStylesheet('/css/bootstrap-responsive.css')
             ->appendStylesheet('/css/bootstrap-responsive.min.css')
             ->appendStylesheet('/css/bootstrap.css');

        echo $this->headLink();
    ?>
    <!-- JS GERAL INICIO -->
    <?php
        $this->headScript()->appendFile('/js/library/jquery.js');
        $this->headScript()->appendFile('/js/library/jquery.dataTables.js');
        $this->headScript()->appendFile('/js/components/grid.js');

        echo $this->headScript();?>
    </head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
	    <div class="container">
	        <div class="nav-collapse collapse">
            <?php echo $this->navigation()?>
	        </div><!--/.nav-collapse -->
	    </div>
	</div>
</div>
<br />
<br />
    <br><br><br>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span3">
            </div>
            <div class="span9">
                <?php echo $this->message()?>
                <?php echo $this->layout()->content ?>
            </div>
        </div>
    </div>
</body>
</html>